name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement", "Needs-Triage"]
assignees:
  - Simnico99
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe. (Optional)
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when
  - type: textarea
    attributes:
      label: Describe alternatives you've considered (Optional)
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Additional context (Optional)
      description: Enter any other applicable info here.
